version: "3.9"

services:
  redis:
    image: redis:7
    container_name: youlisten-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: youlisten-backend
    ports:
      - "4000:4000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
